import type { Product } from "./types"

export const products: Product[] = [
    {
      id: 1,
      title: "Product 1",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1 (1).png",
      description: "High quality modern product",
      price: 120,
      oldPrice: 150,
      rating: 4.5,
      isNew: true,
    },
    {
      id: 2,
      title: "Product 2",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7.png",
      description: "High quality modern product",
      price: 130,
      oldPrice: 160,
      rating: 4.4,
      isNew: false,
    },
    {
      id: 3,
      title: "Product 3",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (1).png",
      description: "High quality modern product",
      price: 140,
      oldPrice: 170,
      rating: 4.6,
      isNew: true,
    },
    {
      id: 4,
      title: "Product 4",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "images/Rectangle 7 (2).png",
      description: "High quality modern product",
      price: 150,
      oldPrice: 180,
      rating: 4.3,
      isNew: false,
    },
    {
      id: 5,
      title: "Product 5",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "images/Rectangle 7 (3).png",
      description: "High quality modern product",
      price: 160,
      oldPrice: 190,
      rating: 4.7,
      isNew: true,
    },
    {
      id: 6,
      title: "Product 6",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1.png",
      description: "High quality modern product",
      price: 170,
      oldPrice: 200,
      rating: 4.2,
      isNew: false,
    },
    {
      id: 7,
      title: "Product 7",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1 (1).png",
      description: "High quality modern product",
      price: 175,
      oldPrice: 210,
      rating: 4.5,
      isNew: true,
    },
    {
      id: 8,
      title: "Product 8",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7.png",
      description: "High quality modern product",
      price: 180,
      oldPrice: 220,
      rating: 4.1,
      isNew: false,
    },
    {
      id: 9,
      title: "Product 9",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (1).png",
      description: "High quality modern product",
      price: 185,
      oldPrice: 225,
      rating: 4.6,
      isNew: true,
    },
    {
      id: 10,
      title: "Product 10",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (2).png",
      description: "High quality modern product",
      price: 190,
      oldPrice: 230,
      rating: 4.3,
      isNew: false,
    },
    {
      id: 11,
      title: "Product 11",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (3).png",
      description: "High quality modern product",
      price: 195,
      oldPrice: 240,
      rating: 4.4,
      isNew: true,
    },
    {
      id: 12,
      title: "Product 12",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1.png",
      description: "High quality modern product",
      price: 200,
      oldPrice: 250,
      rating: 4.2,
      isNew: false,
    },
    {
      id: 13,
      title: "Product 13",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: " /images/Rectangle 7.png",
      description: "High quality modern product",
      price: 205,
      oldPrice: 255,
      rating: 4.6,
      isNew: true,
    },
    {
      id: 14,
      title: "Product 14",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (1).png",
      description: "High quality modern product",
      price: 210,
      oldPrice: 260,
      rating: 4.3,
      isNew: false,
    },
    {
      id: 15,
      title: "Product 15",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (3).png",
      description: "High quality modern product",
      price: 215,
      oldPrice: 270,
      rating: 4.5,
      isNew: true,
    },
    {
      id: 16,
      title: "Product 16",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1.png",
      description: "High quality modern product",
      price: 220,
      oldPrice: 280,
      rating: 4.1,
      isNew: false,
    },
    {
      id: 17,
      title: "Product 17",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (1).png",
      description: "High quality modern product",
      price: 225,
      oldPrice: 285,
      rating: 4.7,
      isNew: true,
    },
    {
      id: 18,
      title: "Product 18",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (2).png",
      description: "High quality modern product",
      price: 230,
      oldPrice: 290,
      rating: 4.2,
      isNew: false,
    },
    {
      id: 19,
      title: "Product 19",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (3).png",
      description: "High quality modern product",
      price: 235,
      oldPrice: 300,
      rating: 4.4,
      isNew: true,
    },
    {
      id: 20,
      title: "Product 20",
      category: 'phone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Iphone 14 pro 1 (1).png",
      description: "High quality modern product",
      price: 240,
      oldPrice: 310,
      rating: 4.3,
      isNew: false,
    },
    {
      id: 21,
      title: "Product 21",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7.png",
      description: "High quality modern product",
      price: 245,
      oldPrice: 320,
      rating: 4.6,
      isNew: true,
    },
    {
      id: 22,
      title: "Product 22",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (1).png",
      description: "High quality modern product",
      price: 250,
      oldPrice: 330,
      rating: 4.1,
      isNew: false,
    },
    {
      id: 23,
      title: "Product 23",
      category: 'laptop',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (2).png",
      description: "High quality modern product",
      price: 255,
      oldPrice: 340,
      rating: 4.5,
      isNew: true,
    },
    {
      id: 24,
      title: "Product 24",
      category: 'earphone',
      shortDesc: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
      image: "/images/Rectangle 7 (3).png",
      description: "High quality modern product",
      price: 260,
      oldPrice: 350,
      rating: 4.4,
      isNew: false,
    },
  ]
  